from os import system
from time import sleep
from colorama import Fore
import sys

system("clear")

bnr = (Fore.LIGHTGREEN_EX+f"""
   
   

                              ⣠⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⡀
                          ⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⡀
                        ⣰⣿⣿⣿⣿⣿⣿⡿⠛⠋⠉⠉⠉⠉⠉⠉⠉⠉⠻⣿⣿⣦⡀
                        ⣿⣿⣿⣿⣿⡿⠋            ⠈⣿⣿⣿⡄
                       ⣿⣿⣿⣿⣿⣿⠁⣀⣤⣶⣶⣶⣤⣤⡀   ⣠⣶⡶⢿⣿⣿⣿
                      ⢸⣿⣿⣿⣿⣿⣧⠞⠋⢀⢀⢀⠈⠻⠿⣷   ⣿⢋⣀⣸⣿⣿⣿⡆
                     ⢠⣿⣿⣿⣿⣿⡟⠁⢀⢠⣶⢾⣿⣿⣿⡿⠃   ⢿⣿⡿⣿⣿⣿⣿⡇
                    ⢠⣿⣿⣿⣿⣿⣿⠇                ⠈⢻⣿⣿⡇
                    ⣿⣿⣿⣿⣿⣿⣿                 ⣀⣿⣿⣿⡇
                    ⣿⣿⣿⣿⣿⣿⣿⡆  ⠛⠻⣿⣯⢀⢀⢀⢰⣶⣶⣶⡄ ⣿⣿⣿⣿⣿⡇
                    ⣿⣿⣿⣿⣿⣿⣿⣿⡄   ⠈⠻⠿⠿⠿⠿⠿⠟⠻⠿⠿⠟⣿⣿⣿⣿⠇
                    ⢹⣿⣿⣿⣿⣿⣿⣿⣿⣄        ⢴⣶⣦  ⣰⣿⣿⣿⣿
                    ⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄     ⠘⣿⡇  ⣿⣿⣿⣿⣿
                    ⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣤⣀  ⣿⣇ ⣾⣿⣿⣿⣿⡟
                ⣠⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄
           ⣀⣤⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡄
        ⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⡀
     ⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣦⣤⣤⣤⣤⡀
   ⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀
 ⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇
 ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆
⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿-------------⣿⣿⣿⣿⣇
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿-sarhang -⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿-------------⣿⣿⣿⣿⣿⡄
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀



⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
""")
for i in bnr:
  sys.stdout.write(i)
  sys.stdout.flush()
  sleep(0.009)
print("")
name = input(Fore.LIGHTYELLOW_EX+"""
 ID User? (@)  : """)
system("clear")
bnr = (Fore.LIGHTGREEN_EX+f"""


ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
  ok    no    ok     ok    no   no   ok   ok   ok   no  ok   ok    ok   no    ok    no    ok    no 
    
""")
for i in bnr:
  sys.stdout.write(i)
  sys.stdout.flush()
  sleep(0.001)
  print('')
  system("clear")
  print('')
  print('')
  print('')
  print('')
  print('This account cannot be fixed, it has all kinds of violations')